// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	cache: KVNamespace;
	SUPABASE_URL: string;
	SUPABASE_KEY: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_KEY: string;
	DB: D1Database;
}
